"""Initial

Revision ID: 473d60d04915
Revises: 9ab5a0048b77
Create Date: 2026-01-18 20:14:40.968965

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "473d60d04915"
down_revision: Union[str, Sequence[str], None] = "9ab5a0048b77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
