"""update models

Revision ID: 4b48ef935f6a
Revises: bbdb36e61860
Create Date: 2026-01-29 22:10:26.522444

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b48ef935f6a"
down_revision: str | Sequence[str] | None = "bbdb36e61860"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "categories", "slug", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "products", "slug", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "slug", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "categories", "slug", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
