"""some update

Revision ID: 5ae51aa90460
Revises: 4b48ef935f6a
Create Date: 2026-01-30 22:15:36.771072

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae51aa90460"
down_revision: Union[str, Sequence[str], None] = "4b48ef935f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "categories", ["name"])
    op.drop_constraint(
        op.f("categories_parent_id_fkey"), "categories", type_="foreignkey"
    )
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("categories_parent_id_fkey"),
        "categories",
        "categories",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "categories", type_="unique")
    # ### end Alembic commands ###
