"""init again and again

Revision ID: b1f461bbd470
Revises:
Create Date: 2026-02-08 01:31:56.614231

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b1f461bbd470"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
